# Generated by Django 6.0.2 on 2026-03-27 14:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('tour_type', models.CharField(blank=True, max_length=32)),
                ('origin', models.CharField(blank=True, max_length=64)),
                ('max_guests', models.CharField(blank=True, max_length=32)),
                ('reviews', models.CharField(blank=True, max_length=64)),
                ('rating', models.CharField(blank=True, max_length=8)),
                ('price_display', models.CharField(blank=True, max_length=64)),
                ('price_currency', models.CharField(blank=True, default='USD', max_length=4)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('detail_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
